# Generated by Django 3.2.9 on 2021-12-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='porduct',
            name='product_image',
            field=models.FileField(blank=True, null=True, upload_to='product_image/'),
        ),
    ]
