# Generated by Django 3.2.9 on 2021-12-05 13:44

from django.db import migrations, models
from product.Utilities.media_path_converter import upload_image_path

class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_porduct_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porduct',
            name='product_image',
            field=models.ImageField(null=True, upload_to=upload_image_path),
        ),
    ]
