# Generated by Django 3.2.9 on 2021-12-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_porduct_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='porduct',
            name='sulg',
            field=models.SlugField(default='abc'),
        ),
    ]
