# Generated by Django 3.2.9 on 2021-12-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_porduct_sulg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porduct',
            name='sulg',
            field=models.SlugField(blank=True),
        ),
    ]
