# Generated by Django 3.2.9 on 2021-12-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_porduct_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porduct',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
