# Generated by Django 3.2.9 on 2021-12-08 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_porduct_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='porduct',
            old_name='active',
            new_name='featured',
        ),
    ]
