# Generated by Django 3.2.9 on 2021-12-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_active',
            field=models.BooleanField(default=True),
        ),
    ]
