# Generated by Django 3.2.9 on 2021-12-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_porduct_active_prduct'),
        ('Tags', '0002_tag_tag_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='tag',
            name='product',
            field=models.ManyToManyField(blank=True, to='product.Porduct'),
        ),
    ]
